### ISSUE TITLE
Can't install ug4 on Mac with OS version 10.14.6, the error comes from BoostForUG4

### ISSUE THREAD

**Issue by qgguan** [UG4/external_BoostForUG4#1]
[ 81%] Building CXX object ugcore/CMakeFiles/ug4.dir/__/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp.o
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:38:20: error: qualified reference to 'archive_exception' is a constructor name rather than a type in this context
archive_exception::archive_exception(
                   ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:37:20: error: C++ requires a type specifier for all declarations
BOOST_ARCHIVE_DECL(BOOST_PP_EMPTY())
                   ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:38:20: error: expected ';' after top level declarator
archive_exception::archive_exception(
                   ^
                   ;
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:39:20: error: expected ')'
    exception_code c, 
                   ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:38:37: note: to match this '('
archive_exception::archive_exception(
                                    ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:39:5: error: calling a protected constructor of class 'boost::archive::archive_exception'
    exception_code c, 
    ^
/usr/local/include/boost/archive/archive_exception.hpp:51:5: note: declared protected here
    archive_exception() BOOST_NOEXCEPT;
    ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:42:3: error: expected ';' after top level declarator
) : 
  ^
  ;
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:43:5: error: unknown type name 'code'
    code(c)
    ^
/Users/tul72426/ug4/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp:43:12: error: expected ';' after top level declarator
    code(c)
           ^
           ;
8 errors generated.
make[2]: *** [ugcore/CMakeFiles/ug4.dir/__/externals/BoostForUG4/libs/serialization/src/archive_exception.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by stephanmg** [comment]
Please post your `cmake` configuration, in particular, state your compiler version/toolchain. Can you also provide `make VERBOSE=1` output?

**Comment by qgguan** [comment]
Dear Stephan,

Here are CMake information:

-- Info: Current options:
-- Info: TARGET:            ugshell (options are: ugshell, libug4, vrl, vrlgrid, libgrid, gridshell, ugplugin, amg, luashell)
-- Info: DIM:               2;3 (options are: 1, 2, 3, ALL, "1;2", "1;3", "2;3")
-- Info: CPU:               1;2 (options are: 1, 2, 3, 4, 5, VAR, ALL, "2;4", "1;3;4" , ...)
-- Info: PRECISION:         double (options are: single, double)
-- Info: STATIC_BUILD:      OFF (options are: ON, OFF)
-- Info: DEBUG:             OFF (options are: ON, OFF)
-- Info: DEBUG_LOGS:        OFF (options are: ON, OFF)
-- Info: PARALLEL:          OFF (options are: ON, OFF)
-- Info: PCL_DEBUG_BARRIER: OFF (options are: ON, OFF)
-- Info: PROFILER:          None (options are: None, Shiny, Scalasca, Vampir, ScoreP)
-- Info: PROFILE_PCL:       OFF (options are: ON, OFF)
-- Info: CPU_FREQ:          OFF (options are: ON, OFF)
-- Info: PROFILE_BRIDGE:    OFF (options are: ON, OFF)
-- Info: LAPACK:            ON (options are: ON, OFF)
-- Info: BLAS:              ON (options are: ON, OFF)
-- Info: INTERNAL_BOOST:    ON (options are: ON, OFF)
-- Info: EMBEDDED_PLUGINS   OFF (options are: ON, OFF)
-- Info: COMPILE_INFO       ON (options are: ON, OFF)
-- Info: USE_LUA2C          ON (options are: ON, OFF)
-- Info: USE_LUAJIT          (options are: ON, OFF)
--
-- Info: External libraries (path which contains the library or ON if you used uginstall):
-- Info: TETGEN:
-- Info: HLIBPRO:
--
-- Info: C   Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc (ID: Clang)
-- Info: C++ Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ (ID: Clang)
--
-- Info: Using CPU Algebra.
CMake Warning at ugcore/cmake/ug_includes.cmake:389 (message):
  WARNING: C Compiler is Clang, might not work with CUDA.  Try cmake
  -DCUDA_HOST_COMPILER=/usr/bin/gcc ..
Call Stack (most recent call first):
  ugcore/CMakeLists.txt:44 (include)


-- Info: compiling with cxx flags:  -Wall -Wno-multichar -Wsign-compare -Wno-unused-local-typedef -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-unneeded-internal-declaration -O3 -DNDEBUG
-- Info: compiling with c flags:  -Wall -Wno-multichar -Wsign-compare -Wno-unused-local-typedef -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-unneeded-internal-declaration -O3 -DNDEBUG
-- Info: Using LUA2C
-- Info: Using LAPACK (Include: , Lib: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework)
-- Info: Using BLAS (Include: , Lib: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework)
-- Info: Including Boost from /usr/local/include
-- Info: COMPILE_INFO enabled. Causes relinking on each run of make.
--
-- Info: Enabled plugins:
--       ConvectionDiffusion, Electromagnetism, NavierStokes,
--       SmallStrainMechanics,
-- Info: Disabled plugins:
--
-- Hint: To enable/disable a plugin 'PLUGIN_NAME' use the cmake option: -DPLUGIN_NAME=ON/OFF
--
-- Info: SHELLTYPE: linenoise (options are: linenoise, readline, simple)
--
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tul72426/ug4/build

On Nov 20, 2019, at 10:20 AM, Stephan Grein <notifications@github.com<mailto:notifications@github.com>> wrote:

VERBOSE=1

**Comment by stephanmg** [comment]
Can you post `clang --version` too?

**Comment by qgguan** [comment]
clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


On Nov 20, 2019, at 10:43 AM, Stephan Grein <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post clang --version too?

**Comment by stephanmg** [comment]
Just out of curiosity is the compilation successful with `GCC` instead of `clang`?

**Comment by qgguan** [comment]
Dear Stephan,

I can’t install gcc on Mac.
But on Linux machine, of course it works.

Thanks and best regards,
Qingguang Guan

On Nov 20, 2019, at 10:58 AM, Stephan Grein <notifications@github.com<mailto:notifications@github.com>> wrote:


Just out of curiosity is the compilation successful with GCC instead of clang?

**Comment by bsumirak** [comment]
Had a similar issue (maybe the same) when first upgrading to Mojave.
I do not recall exactly what the problem was, but I seem to remember having resolved the issue by installing the current version of Apple's command line tools (and just to be sure by creating a clean new build directory).
Working for me with 10.14.6 and (Apple) clang 11.0.0.

**Comment by qgguan** [comment]
Thanks a lot. I will try.

On Nov 20, 2019, at 4:20 PM, bsumirak <notifications@github.com<mailto:notifications@github.com>> wrote:


Had a similar issue (maybe the same) when first upgrading to Mojave.
I do not recall exactly what the problem was, but I seem to remember having resolved the issue by installing the current version of Apple's command line tools (and just to be sure by creating a clean new build directory).
Working for me with 10.14.6 and (Apple) clang 11.0.0.

**Comment by stephanmg** [comment]
As a side note @Newhat you can of course install the GCC toolchain with `homebrew` or `macports` on Mac.

**Comment by qgguan** [comment]
Finally, the problem was solved by removing the "boost.." files in /usr/local/lib/ and /usr/local/Cellar/ which were created by installing other software.

**Comment by bsumirak** [comment]
Indeed, the compiler even told you it was using a header from the wrong boost installation (sorry I missed that):

> /usr/local/include/boost/archive/archive_exception.hpp:51:5: note: declared protected here
> archive_exception() BOOST_NOEXCEPT;

Would be interesting to know how it got included. Apparently, /usr/local/include was searched before $UG4_ROOT/externals/BoostForUG4. Question is why.

**Comment by stephanmg** [comment]
I think header files will be searched in the provided include paths, I assume, that the `/usr/local/include` precedes the ug include path.
